### PR TITLE
Bump toolchain to 2022-10-27

### PR DESCRIPTION
**Pull request by mpenciak**
Notable changes:
* `RBTree` -> `RBSet`
* Include `manifest.json`

### CODE REVIEW

**Comment by mhuisi** [comment]
There is a branch `nightly` that tracks nightly releases, whereas `main` tracks milestone releases. Please check the README.

**Comment by mpenciak** [comment]
Oh thank you for pointing that out, sorry about the PR to the main branch. Would you be open to a PR to nightly using Std4's `Option.join` and adding the `manifest.json`? (these were a couple issues that came up in my use-case)

**Comment by mhuisi** [comment]
I'd prefer not to depend on Std4 for a single one-liner, since then lean4-cli must update whenever one of Std4 / Lean 4 update in a breaking-manner, and may not be compatible with the most recent Lean 4 build because Std4 hasn't updated yet, propagating the update latency downstream (e.g. to doc-gen4, which also doesn't use Std4).

What is your use-case, and could you do without lean4-cli depending on Std4?

**Comment by mhuisi** [comment]
... If your main issue is the name clash with Std4's `Option.join`, then I propose that I'll just rename the function.

**Comment by Vtec234** [comment]
@mhuisi please do rename -- it is currently not possible to import `Cli` and `Std` in the same file.

**Comment by mhuisi** [comment]
> @mhuisi please do rename -- it is currently not possible to import `Cli` and `Std` in the same file.

I've moved all utility functions into the `Cli` namespace now so that this doesn't happen again.

**Comment by mhuisi** [comment]
@mpenciak Can I close this PR, or is there still something that you'd like this PR to do?

**Comment by mpenciak** [comment]
Yes! Sorry, I should have closed it earlier. Everything is in working order now. Thank you!

**Pull request closed without merging**
